CREATE TABLE tblAccountHolderCU 
( 
  AccountHolderID INTEGER PRIMARY KEY IDENTITY(1,1) NOT NULL,
  AHFirstName NVARCHAR(256) NOT NULL,
  AHSurname NVARCHAR(256) NOT NULL,
  AHEmail NVARCHAR(256) NOT NULL,
  AHPhone NVARCHAR(256) NOT NULL,
  AHAddress1 NVARCHAR(256) NOT NULL,
  AHAddress2 NVARCHAR(256) NULL,
  AHCity NVARCHAR(256) NOT NULL,
  AHCounty NVARCHAR(256) NOT NULL 
)